# Generated by Django 6.0 on 2025-12-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_jointrip_id_alter_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointrip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
