# Generated by Django 6.0 on 2025-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0002_alter_tripsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
