# Generated by Django 6.0 on 2025-12-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_subscription', '0005_merge_20251224_1526'),
        ('trips', '0010_alter_jointrip_id_alter_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsubscription',
            name='join_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='trips.jointrip'),
        ),
    ]
