# Generated by Django 6.0 on 2025-12-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_request', '0007_remove_joinrequesttrip_reject_comment_and_more'),
        ('riders', '0007_alter_reviewrider_id_alter_rider_id'),
        ('trip_subscription', '0006_alter_tripsubscription_join_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsubscription',
            name='join_request_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='rider_request.joinrequesttrip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripsubscription',
            unique_together={('rider', 'join_request_trip')},
        ),
    ]
